version: '2.2'

services:
  mysql:
    image: mariadb:10.4.19
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      #- MYSQL_DATABASE=${MYSQL_DATABASE}
      #- MYSQL_USER=${MYSQL_USER}
      #- MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
  backend:
    image: buianhduc/ytb-demo:0.0.1-SNAPSHOT
    hostname: backend
    ports:
      - 8080:8080
  frontend:
    image: buianhduc/ytb-frontend:0.1.0
    hostname: frontend
    ports:
      - 80:5173
volumes:
  mariadb_data:
