version: '2.2'

services:
  mysql:
    image: mariadb:10.4.19
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      #- MYSQL_DATABASE=${MYSQL_DATABASE}
      #- MYSQL_USER=${MYSQL_USER}
      #- MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data: